#! /bin/sh

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝

sxhkd &
nm-applet --indicator &
xset s off -dpms

########################################################################
#                            M O N I T O R S                           #
########################################################################

xrandr --output HDMI-1 --primary --left-of eDP-1 --size 1920x1080 &

bspc subscribe monitor | while read -r line; do
  case $line in monitor_add*|monitor_geometry*)
	if [[ "$(xrandr | grep -w "HDMI-1 connected")" == *"HDMI-1 connected"* ]] 
        then          
            #bspc monitor eDP-1 -d " 8" " 9" " 0"
            bspc monitor eDP-1 -d "8" "9" "0"
            #bspc monitor HDMI-1 -d " 1" " 2" " 3" " 4" " 5" " 6" " 7"
            bspc monitor HDMI-1 -d "1" "2" "3" "4" "5" "6" "7"

    else
        bspc monitor -d "1" "2" "3" "4" "5" "6" "7" "8" "9" "0"

    fi
    ;;
  *)
  ;;
esac
done &

#bspc wm --adopt-orphans

########################################################################
#                           A U T O S T A R T                          #
########################################################################

picom --experimental-backends &
/home/sergio/.config/polybar/launch_two.sh &

########################################################################
#                         A P P E A R A N C E                          #
########################################################################

bspc config border_width         2
bspc config window_gap           4

bspc config normal_border_color "#0a0a17"
bspc config active_border_color "#0a0a17"
bspc config focused_border_color "#383d63"
bspc config presel_feedback_color "#383d63"

mark-ovredir-focused = false

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

########################################################################
#                              R U L E S                               #
########################################################################

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Pavucontrol state=floating follow=on rectangle=630x630 center=true
bspc rule -a Pcmanfm state=floating center=true
bspc rule -a Gnome-calculator state=floating follow=on
bspc rule -a Blueman-manager state=floating follow=on center=true
bspc rule -a MEGAsync state=floating follow=on rectangle=402x569 center=true

bspc config pointer_modifier mod4 # mod4 = super key
bspc config pointer_action1 move # super + left click
bspc config pointer_action2 resize_corner # super + right click


